services:
  - type: web
    plan: free
    name: Rename-Render
    env: python
    buildCommand: gunicorn app:app & python3 bot.py
    startCommand: python3 bot.py
    repo: https://github.com/Gitverse-prg/Rename-Render/new/TECH_VJ.git
    branch: TECH_VJ
    autoDeploy: True
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMIN
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: DB_URL
        sync: false
      - key: DB_NAME
        sync: false
